lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    
    # Configuration des cookies pour stocker le JWT
    set_cookies:
        BEARER:
            lifetime: 3600
            samesite: lax
            path: /
            domain: null
            secure: true  # Mettre Ã  true en production avec HTTPS
            httpOnly: true
    
    # Configuration pour extraire le token depuis le cookie
    token_extractors:
        cookie:
            enabled: true
            name: BEARER
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization