lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    api_platform:
        check_path: /api/login_check
        username_path: email
        password_path: security.credentials.password
    set_cookies:
        BEARER:
            lifetime: 3600
            path: /
            domain: localhost
            secure: false        # true en prod (https)
            httpOnly: true      # ‚≠ê IMPORTANT
            samesite: lax